import unittest
from tvl_helpers import *

CHECK_INDUSTRY_FILE_NAMES = ['Advertising& Marketing',
                             'Aerospace& Defense',
                             'AgriculturalProducts',
                             'AirFreight & Logistics',
                             'Airlines',
                             'AlcoholicBeverages',
                             'Apparel,Accessories & Foo',
                             'ApplianceManufacturing',
                             'AssetManagement & Custody',
                             'AutoParts',
                             'Automobiles',
                             'Biofuels',
                             'Biotechnology& Pharmaceut',
                             'BuildingProducts & Furnis',
                             'CarRental & Leasing',
                             'Casinos& Gaming',
                             'Chemicals',
                             'CoalOperations',
                             'CommercialBanks',
                             'ConstructionMaterials',
                             'ConsumerFinance',
                             'Containers& Packaging',
                             'CruiseLines',
                             'DrugRetailers',
                             'E-Commerce',
                             'Education',
                             'ElectricUtilities & Power',
                             'Electrical& Electronic Eq',
                             'ElectronicManufacturing S',
                             'Engineering& Construction',
                             'FoodRetailers & Distribut',
                             'ForestryManagement',
                             'FuelCells & Industrial Ba',
                             'GasUtilities & Distributo',
                             'Hardware',
                             'HealthCare Delivery',
                             'HealthCare Distributors',
                             'HomeBuilders',
                             'Hotels& Lodging',
                             'Household& Personal Produ',
                             'IndustrialMachinery & Goo',
                             'Insurance',
                             'InternetMedia & Services',
                             'InvestmentBanking & Broke',
                             'Iron& Steel Producers',
                             'LeisureFacilities',
                             'ManagedCare',
                             'MarineTransportation',
                             'Meat,Poultry & Dairy',
                             'Media& Entertainment',
                             'MedicalEquipment & Suppli',
                             'Metals& Mining',
                             'MortgageFinance',
                             'Multilineand Specialty Re',
                             'Non-AlcoholicBeverages',
                             'Oil& Gas - Exploration & ',
                             'Oil& Gas - Midstream',
                             'Oil& Gas - Refining & Mar',
                             'Oil& Gas - Services',
                             'ProcessedFoods',
                             'Professional& Commercial ',
                             'Pulp& Paper Products',
                             'RailTransportation',
                             'RealEstate',
                             'RealEstate Services',
                             'Restaurants',
                             'RoadTransportation',
                             'Security& Commodity Excha',
                             'Semiconductors',
                             'Software& IT Services',
                             'SolarTechnology & Project',
                             'TelecommunicationServices',
                             'Tobacco',
                             'Toys& Sporting Goods',
                             'WasteManagement',
                             'WaterUtilities & Services',
                             'WindTechnology & Project ']


class MyTestCase(unittest.TestCase):
    def test_gather_file_names_for_all_industries(self):
        industry_files = gather_file_names_for_all_industries()
        self.assertEqual(sorted(list(industry_files.keys())), CHECK_INDUSTRY_FILE_NAMES)
        self.assertEqual(len(industry_files['Non-AlcoholicBeverages']), 6)


if __name__ == '__main__':
    unittest.main()
